defog-ai/defog

defog/__init__.py
From a logging/informing the developer PoV: Nicer to specify which question are we talking about, helps match the context quickly against the generated query + response
=> Include question in the print

defog/__init__.py, defog/cli.py, defog/util.py, requirements.txt, setup.py
**Motivation**:  While we have specific instructions in the metadata cookbook for users to enumerate categorical variables in the generated schema, in reality, few users manually made these changes. This would lead to errors when users later generated queries. 
**Changes made**: 
To make this process smoother, we can automatically highlight any columns that are likely to be categorical variables and enumerate possible values in the column descriptions. To do this:
1. We define indicators that a column has categorical variables. We looked at two approaches: 
(a) whether the ratio of unique values to total values in a column is below a certain cutoff (eg, 2%). While this works for a smaller number of rows, it did not make sense for larger numbers of rows. For eg, a column with 10000 total …
=> Checks for likely categorical variables in databases 

.github/workflows/main.yml, README.md, defog/__init__.py, defog/cli.py, defog/query.py, defog/util.py, requirements.txt, tests/test_query.py, tests/test_util.py
Fixes for feedback logging [DEF-102](https://linear.app/defog/issue/DEF-102/fix-the-python-library-to-avoid-loggingfixing-connection-errors):
- query.py: we exclude connection errors from logging
- cli.py: refactor feedback solicitation after query generation to use a separate function `util.get_feedback`
- remove an unused function
- update requirements.txt
- add tests
- streamline workflows
=> Fix feedback logging

defog/util.py, setup.py, tests/test_util.py
Formatting of excessively long values with non-standard characters broke the table metadata csv conversion. Eg:
```
$ defog gen
Connection details found. Reading connection details from file...
Connection details read from /Users/jp/.defog/connection.json.
defog gen requires a list of tables to generate. Please enter the names of the tables whose schema you would like to generate, separated by a space:
<redacted_table_name>
Do you want to automatically scan these tables to determine which column might be categorical? The distinct values in each column likely to be a categorical column will be sent to our server. (y/n)
y
Getting schema for each table that you selected...
Identifying categorical columns in <redacted_table_name>. This might take a while if you have many rows in your table. …
```
=> [Bug Fix] Fixed issue when getting excessively long column values with unexpected characters.

.gitignore, defog/admin_methods.py, defog/cli.py
Add ability to "get", "add", "delete" golden queries using the cli.
Updated the admin methods to consistently export to a default path regardless of format, and to always return the golden queries object.
Usage tests:
```
$ defog golden add golden_queries.json
Connection details found. Reading connection details from file...
Connection details read from /Users/jp/.defog/connection.json.
Golden queries have been received by the system, and will be processed shortly...
Once that is done, you should be able to see improved results for your questions.
$ defog golden get json
Connection details found. Reading connection details from file...
Connection details read from /Users/jp/.defog/connection.json.
Getting golden queries...
2 golden queries exported to golden_queries.json
You have 2 golden …
```
=> Add crud for golden queries in cli

.gitignore, defog/admin_methods.py, defog/cli.py, setup.py
Add glossary actions in cli. We now support getting, updating, and deleting glossaries from the cli:
- defog glossary get
- defog glossary update (will prompt for path next)
- defog glossary delete
Tests below:
```
$ defog glossary get
Connection details found. Reading connection details from file...
Connection details read from /Users/jp/.defog/connection.json.
You don't have a glossary yet.
$ cat glossary.txt
customer_id can be used to join accounts and customers table%
$ defog glossary update
Connection details found. Reading connection details from file...
Connection details read from /Users/jp/.defog/connection.json.
defog glossary update requires a path to a .txt file containing your glossary:
glossary.txt
Your glossary has been updated.
$ defog glossary get
Connection details …
```
=> Add glossary actions in cli

defog/__init__.py, defog/admin_methods.py, defog/cli.py, setup.py
Added a new command to our CLI: `defog vet metadata <csv_path>`
This will check each row and if the character length of the column description exceeds 100, it will send a request to our backend to propose a shortened version.
It will prompt the user with the shortened version to see if the user wants to accept it or not, and will only save it back to the csv if the user agrees (enters 'y').
The user can propose edits on the suggested description.
```sh
$ defog vet metadata defog_metadata.csv
Column description for username is > 100 characters.
Old description: Email of the user. Possible values are abc@gmail.com, def@microsoft.com, brickworks123@elevate.com, alan@sofi.com, kbdfans@neurips.org
Suggested description: Email of the user. Format: [username]@[domain].com
Do you want to save …
```
=> [CLI] defog vet metadata

defog/admin_methods.py, defog/cli.py, defog/util.py, setup.py, tests/test_util.py
Add call to `/reflect_on_error` if negative feedback received, and then display the suggestions for validation from the user. Here is a test run where we only updated the glossary but not the column descriptions or reference queries after. Requerying in the CLI after that magically works!:
```sh
$ defog query "how many users made long requests"
Generating the query for your question: how many users made long requests...
Query generated, now running it on your database...
Defog generated the following query to answer your question:
SELECT COUNT(DISTINCT defog_api_stats.api_key)
FROM defog_api_stats
WHERE defog_api_stats.requested_at::TIMESTAMP > CURRENT_TIMESTAMP - INTERVAL '10 minutes';
Results:
count |
------|
2     |
Did Defog answer your question well? Just hit enter to skip (y/n):
n …
```
=> Add reflection + validation steps in get_feedback

defog/__init__.py, setup.py
=> generate_query_url now uses base_url by default, instead of being hard-coded to api.defog.ai

defog/admin_methods.py, defog/query_methods.py, setup.py
This will make more sense with a new PR that's coming up on the backend repo! For now, adding this param will not have any effect
=> Added dev mode parameter for methods that can use it

defog/query_methods.py, setup.py
This adds a `generation_time_taken` and `execution_time_taken` parameter to the `run_query` and `get_query` methods. This will help Defog users understand if a given query is taken too long to execute and/or generate, and optimize instructions or their database accordingly.
To test this,
```python
from defog import Defog
defog = Defog()
defog.run_query("how many rows are in the table", profile=True)
```
The resulting dict option will have the keys `execution_time_taken`, and `generation_time_taken`
=> Add profile option to time query generation and execution

defog/admin_methods.py, setup.py
This is useful in situations where we have metadata that has been previously provided as - say - a CSV. With this, we can create empty tables that match the metadata, and test the model's performance.
=> added a method for creating an empty table, given metadata

defog/admin_methods.py, defog/generate_schema.py, defog/query.py, setup.py
If SQLServer users want to connect to multiple databases (and not be tied to just a single DB), they can now do so by specifying an empty string for database. 
A cleaner implementation + documentation for this coming soon. Will just leave your PR open until then.
=> Enable multiple DBs on SQLServer

defog/generate_schema.py, setup.py
To test
```python
from defog import Defog
defog = Defog(DEFOG_API_KEY, db_type="bigquery", db_creds={"json_key_path": "/path/to/bq.json"})
defog.generate_db_schema(tables=[], return_tables_only=True)
```
=> Enable bigquery to determine table names if tables names are not provided

defog/query.py, defog/query_methods.py, setup.py
This ensures that the `/feedback` and `/retry_query_with_error` functions utilize the base url
=> Ensure that the `execute_query` method uses a base_url parameter

defog/generate_schema.py, setup.py
Previously, Defog we would not show tables/views that were not part of the default schema. 
From a customer's email:
> Currently, in the select tables dropdown Defog is only able to detect the tables/views that are a part of the default schema. If I want to add tables from a schema, I would need to manually paste it in like so: <schema_name>.<table_name> 
With this PR, this is now fixed. A corresponding fix in defog-self-hosted is coming up
=> Return table names in postgres for non 'public' schemas, too

.gitignore, defog/__init__.py, defog/async_admin_methods.py, defog/async_generate_schema.py, defog/async_health_methods.py, defog/async_query_methods.py, defog/generate_schema.py, defog/query.py, defog/util.py, requirements.txt, tests/test_async_defog.py, tests/test_query.py
For `postgres` and `redshift`, we have the asynchronous `asyncpg` to replace `psycopg2`
For `mysql`, we have `aiomysql` to replace `mysql.converter`
For `snowflake`, we use the same connector as it also offers a `cur.execute_async` method- we then poll the status of the query id to see if its done running otherwise just simulate an async sleep using `await asyncio.sleep(1) `.
For `sqlserver`, we use `aioodbc` which has the exact same signature as `pyodbc` but is asynchronous and must be awaited.
However, for `Databricks` and `BigQuery`, no native asynchronous alternatives were found. To mimic asynchronous behavior for these databases, we are using `asyncio.to_thread` to handle blocking operations in a non-blocking manner.
Methods of `AsyncDefog` have the exact same signature (name, …
=> AsyncDefog

defog/admin_methods.py, defog/async_admin_methods.py, defog/cli.py, defog/generate_schema.py, defog/health_methods.py, defog/query.py, defog/query_methods.py, defog/util.py, requirements.txt, setup.py, tests/test_query.py
This PR primarily does 2 things:
1. Adds `verify=False` to all HTTP requests. This ensures that the python library can run on machines that do not have a way to verify server side SSL certificates
2. Fixes the logic for generating metadata in postgres databases when querying from non default schemas
This has been pushed to pypi and has been tested in `defog-self-hosted`, so merging for now to minimize distractions for everyone else.
=> Remove SSL verification, add better support for postgres metadata generation with schemas

defog/async_generate_schema.py, defog/generate_schema.py, setup.py
- Modify `generate_postgres_schema` to return custom data types and their enum labels.
- Added `get_postgres_triggers` and `get_postgres_functions` methods to retrieve custom functions and triggers.
=> Custom data types

defog/llm/models.py, defog/llm/utils.py, defog/llm/utils_function_calling.py, tests/test_llm_tool_calls.py
Removed pydantic schema for `tool_choice`. OpenAI and Anthropic have very different inputs for this parameter. 
| Feature                      | OpenAI                                      | Anthropic                                  |
|------------------------------|---------------------------------------------|--------------------------------------------|
| Zero or more tools called    | `auto`                                      | `{"type": "auto"}`                        |
| At least one tool must be called | `required`                               | `{"type": "any"}`                         |
| Specific tool called         | `{"type": "function", "function": {"name": function_name}}` | `{"type": "tool", "name": function_name}` |
We hence simplify things by allowing the input to the …
=> Tool Call Improvements

defog/llm/utils.py, setup.py
The `input_tokens`, `output_tokens`, and `cost_in_cents` previously only reflected values for a single message.
This was fine when we had not incorporated tool use into this library. But with tool use, there are multiple messages sent to the LLM.
This PR amends the way we were calculated these to take multiple messages into account.
=> Update token usage and cost, taking tool use into account

defog/llm/utils.py, defog/llm/utils_function_calling.py, tests/test_llm_tool_calls.py
- `chat_gemini_async` and `chat_gemini` now both support function calling.
- Note that in `get_function_specs`, we now remove `default` and `title` keys from the input_schema as these extra fields are not accepted in gemini and are not required in OpenAI/Anthropic models.
- For gemini, all "type" values in the input_schema have to be in uppercase.
- Removed unused `store` and `metadata` params for gemini.
- New tool use tests for gemini 
- Update token usage for gemini in line with #73 
- Added `post_tool_function` for gemini chats in line with #72 
- added missing `post_tool_function` param to `chat_anthropic`
- added more constraints in new `verify_post_tool_function` to check that `post_tool_function` has the right parameters
- rephrased arithmetic question slightly as gemini tends to …
=> Gemini tool support

defog/llm/utils.py, requirements.txt, setup.py, tests/test_llm_tool_calls.py
Added a `tool_id` to `tool_outputs` for better tracking. This only works for OpenAI and Anthropic, and is `None` for Gemini as Gemini (strangely) does not return a tool id – despite having a field for it.
Removed the `tools_used` field from `LLMResponse`, since those can be easily extracted from `tool_outputs`.
We now use the latest version of the `google-genai`, `openai`, and `anthropic` libraries
=> Refactor tool use response

defog/__init__.py
Add function signatures so that we get the function definitions when importing and using the function in other projects that import `defog`. This is specific only to the functions that are added via the blocks performing `setattr(Defog, name, attr)` in `__init__.py`.
We now can see the full function signature for these imported functions in DSH:
=> Add function signatures

defog/llm/utils.py, setup.py
Previously, we would often get max tokens reached errors with `chat_async` when `max_completion_tokens` was not explicitly set, as those used a default max tokens value of 4096. This was a particular issue with reasoning models.
This PR fixes this by setting `max_completion_tokens` to `None` for all providers that support this. For Anthropic, it is currently hard-coded to 8191 since Anthropic does not support `None` as a valid value.
=> Set default max tokens to None to avoid max token errors

defog/llm/mcp_readme.md, defog/llm/utils_mcp.py, requirements.txt, setup.py, tests/mcp/mcp_arithmetic_sse.py, tests/mcp/mcp_arithmetic_stdio.py, tests/mcp/test_mcp.py
[Model Context Protocol](https://github.com/modelcontextprotocol) provides a standardized way for LLMs to use external tools. This PR adds support for connecting to MCP servers and letting models use tools working with both Anthropic, OpenAI and Gemini models.
- Add a complete MCP client implementation for connecting to both SSE and stdio MCP servers
- Add comprehensive testing suite with live API and server connection tests
- Integrate with current Anthropic, OpenAI and Gemini API handling
```
from defog.llm.utils_mcp import initialize_mcp_client
client = await initialize_mcp_client("path/to/config.json",
"claude-3-haiku")
response, tool_outputs = await client.mcp_chat("Use tools to help me
multiply 12 and 34")
await client.cleanup()
```
=> Add MCP (Model Control Protocol) Client Support

defog/llm/utils.py, setup.py
We now add fallbacks to structured output handling. This is useful when the LLM uses markdown or other artifacts to the JSON returned instead of just outputting clean JSON.
This _should_ handle this issue: https://github.com/defog-ai/introspect/issues/479
=> Better structured outputs handling

defog/llm/code_interp.py, tests/test_code_interp.py
This PR adds a cross-LLM code interpreter tool for OpenAI, Anthropic, and Gemini models.
The tool assumes a compulsory `csv_string` and `question` – and only outputs code + resulting text. 
TODO:
- add image outputs as well
- make csv_string optional, and maybe take it more varied inputs (images, PDFs etc)
=> Add a cross-LLM code interpreter tool

defog/llm/citations.py, defog/llm/providers/anthropic_provider.py, defog/llm/providers/openai_provider.py, setup.py, tests/test_llm.py, tests/test_llm_tool_calls.py
This adds support for thinking for all Anthropic models after Claude 3.7 Sonnet.
Now, thinking can be used both as part of tool calls and as standalone.
To keep this consistent with the OpenAI API, we keep a `reasoning_effort` param. When `reasoning_effort` is one of the following parameters, we use the following thinking budgets:
- `low`: 2048
- `medium`: 4096
- `high`: 8192
Tests have been updated to incorporate this.
=> Enable extended thinking for Claude 3.7 Sonnet and up models

defog/llm/config/settings.py, defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/openai_provider.py, defog/llm/providers/together_provider.py, defog/llm/tools/handler.py, defog/llm/utils.py, defog/llm/utils_function_calling.py, setup.py, tests/test_llm_tool_calls.py
With the Claude 4 models, parallel tool calls are [finally intelligent enough](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/claude-4-best-practices#optimize-parallel-tool-calling) to use in production.
In this PR, we enable parallel tool calls and update tests to verify completion.
We also fix a minor issue in `chat_async` – creating deep copies of input messages, instead of modifying them directly.
This is enable by default, but can be disabled like so:
```python
config_sequential = LLMConfig(enable_parallel_tool_calls=False)
result_sequential = await chat_async(
provider="openai",
model="gpt-4.1",
messages=messages,
tools=[...],
config=config_sequential,
)
```
It is recommended to do keep parallel tool calls enabled for Claude 4 models. But for best results, …
=> Enable parallel tool calling by default

defog/__init__.py, defog/admin_methods.py, defog/async_generate_schema.py, defog/async_query_methods.py, defog/cli.py, defog/generate_schema.py, defog/health_methods.py, defog/llm/sql_generator.py, defog/local_metadata_extractor.py, defog/metadata_cache.py, defog/query.py, defog/query_methods.py, defog/util.py, tests/test_async_defog.py, tests/test_defog.py, tests/test_local_metadata_extractor.py, tests/test_metadata_cache.py, tests/test_query.py, tests/test_sql_generator.py
> [!NOTE]
> Instead of routing SQL generation queries through api.defog.ai, we now give users the ability to run these queries completely locally
- Added local metadata extraction functionality to extract table schemas directly from databases
- Implemented SQL generation capabilities with LLM provider support
- Added comprehensive test coverage for new features
- Support for direct LLM usage for SQL generation with configurable provider and model
- Metadata extraction from databases when table metadata is not provided
- Schema caching implementation to improve performance
- Removal of unnecessary `verify=False` parameters
- Added 724 lines of test coverage across 3 new test files:
- `test_local_metadata_extractor.py`: Tests for metadata extraction functionality
- `test_metadata_cache.py`: …
=> Add local metadata extraction and SQL generation capabilities

defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/deepseek_provider.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/mistral_provider.py, defog/llm/providers/openai_provider.py, defog/llm/providers/together_provider.py, defog/llm/utils.py, tests/test_llm.py, tests/test_llm_tool_calls.py
- Refactored LLM provider implementations to reduce code duplication
- Migrated from `parse_obj` to `model_validate` for Anthropic/Claude provider
- Removed o1 model from tests
- Updated test suite to reflect provider changes
- **Net reduction: 89 lines of code removed**
- **Provider Refactoring**: Extracted common functionality into base provider class
- **Pydantic Migration**: Updated Anthropic provider to use `model_validate` instead of deprecated `parse_obj`
- **Test Updates**: Removed o1 model references and updated tests for new provider structure
- **Code Cleanup**: Reduced overall codebase by 89 lines through deduplication (305 insertions, 394 deletions)
=> Refactor LLM providers

CLAUDE.md, README.md, defog/llm/html_data_extractor.py, docs/data-extraction.md, tests/test_html_data_extractor.py
- Adds the ability to extract structured data from images embedded in HTML documents
- Leverages the existing ImageDataExtractor to process charts, graphs, and image-based tables found in HTML
- Maintains backward compatibility with an optional `enable_image_extraction` parameter (default: True)
- **Integration**: Added ImageDataExtractor as a dependency in HTMLDataExtractor
- **Analysis**: Updated HTML analysis prompt to identify `<img>` tags as potential data sources
- **Extraction**: Added logic to extract image URLs and process them through the image extractor
- **Tests**: Added comprehensive test coverage for the new functionality
- **Documentation**: Updated docs to describe image extraction capabilities
=> Add image data extraction support to HTML data extractor

defog/__init__.py, defog/async_admin_methods.py, defog/async_generate_schema.py, defog/generate_schema.py, defog/llm/exploration_executor.py, defog/llm/providers/gemini_provider.py, defog/llm/utils_function_calling.py, defog/llm/utils_memory.py, defog/query.py, examples/enhanced_orchestrator_example.py, examples/orchestrator_dynamic_example.py, examples/schema_documentation_example.py, examples/sql_agent_example.py, pyproject.toml, tests/test_duckdb_connector.py, tests/test_enhanced_orchestrator.py, tests/test_local_metadata_extractor.py, tests/test_memory.py, tests/test_orchestrator_e2e.py, tests/test_write_security.py
This PR fixes all critical ruff linting errors identified in the codebase, reducing the error count from 77 to 0 for the targeted error types.
- **F841 (33 instances)**: Removed unused variable assignments in `async_generate_schema.py` and `generate_schema.py`
- **E722 (20 instances)**: Replaced bare `except:` clauses with specific exception types (`ImportError` or `Exception`)
- **F821 (12 instances)**: 
- Fixed variable name typo (`conn` → `con`) in `async_admin_methods.py`
- Added file-level `# ruff: noqa: F821` ignores for template code false positives
- **E402 (8 instances)**: Configured ruff to ignore module-import-not-at-top-of-file via `pyproject.toml`
- **F401 (3 instances)**: Removed unused imports (`Dict`, `List`, `Any`) from `__init__.py`
- **E721 (1 instance)**: Replaced …
=> Fix ruff linting errors

defog/llm/providers/base.py, defog/llm/utils.py, docs/llm-utilities.md, tests/test_tool_citations.py
- Add `insert_tool_citations` parameter to `chat_async` that automatically adds citations when tools are used
- Works with OpenAI and Anthropic providers only (raises error for other providers)
- Leverages existing `citations_tool` to process tool outputs as source documents
- Add `insert_tool_citations: bool = False` parameter to `chat_async`
- Add `citations: Optional[List[Dict[str, Any]]]` field to `LLMResponse` 
- Implement citation processing after tool execution
- Add helper functions to convert tool outputs and extract user questions
- Add comprehensive tests with real end-to-end examples
- Update documentation with examples
```python
from pydantic import BaseModel
from defog.llm.utils import chat_async
from defog.llm.llm_providers import LLMProvider
class WeatherInput(BaseModel): …
```
=> Add tool citations support to chat_async

CLAUDE.md, README.md, defog/llm/memory/token_counter.py, defog/llm/tools/handler.py, defog/llm/utils.py, tests/test_tool_output_validation.py
- Added token counting functionality for tool outputs
- Implemented validation to check if tool outputs exceed configurable token limits
- Integrated validation into tool execution pipeline to prevent context overflow
When tools return very large outputs (e.g., reading large files, database queries with many results), these outputs can exceed the LLM's context window, causing errors or degraded performance. There was no mechanism to validate tool output sizes before passing them to the LLM.
Implemented a token-based validation system that:
1. Counts tokens for any type of tool output (strings, dicts, lists, objects)
2. Validates outputs against a configurable token limit (default: 10,000 tokens)
3. Returns a user-friendly error message when outputs are too large
**In `TokenCounter` …
=> Add tool output size validation to prevent LLM context overflow

README.md, README_MCP.md, defog/mcp_server.py
Claude Desktop only seems to support `stdio` based local MCPs for now, so the MCP server has been moved to an stdio based one instead of a `streamable-http` based one.
With this, it works quite well with Claude Desktop!
=> Migrate mcp server from streamable-http to stdio

README.md, README_MCP.md, defog/mcp_server.py, setup.py
- Implements GitHub issue #151
- Adds a new `list_database_schema` tool to the MCP server that lists all tables and their schemas
- Helps LLMs understand what data is available in the database for querying
The new tool:
- Returns table names, column names, and data types for all tables in the database
- Supports all database types (postgres, mysql, bigquery, snowflake, databricks, sqlserver, sqlite, duckdb, redshift)
- Includes table descriptions when available (for databases that support it)
- Provides summary statistics showing total tables and columns
- Only available when database credentials are properly configured
- Reuses the existing `extract_metadata_from_db_async` function for consistency
- Tested with existing MCP tests
- All linting checks pass (ruff check and ruff format)
- …
=> feat: add list_database_schema tool to MCP server

README_MCP.md, defog/llm/text_data_extractor.py, defog/mcp_server.py, setup.py
- Added `extract_html_data` tool to extract structured data from HTML content (tables, lists, key-value pairs)
- Added `extract_text_data` tool to extract structured data from plain text files (Q&A pairs, tables, lists, metrics)
- Both tools support multiple LLM providers (OpenAI with o3, Anthropic with Claude 4 Sonnet, Gemini with Pro 2.5)
- Updated MCP documentation to include the new extraction tools
- Minor prompt refinement in text data extractor to focus on numerical data
=> Add HTML and text data extraction tools to MCP server

defog/cli.py, defog/mcp_server.py, setup.py
- Fixed issue where MCP server doesn't read the latest config file on first run
- Added optional `--transport` and `--port` arguments to customize MCP server transport
The MCP server was validating database credentials at module import time, before the CLI wizard had a chance to update the config file. This caused the server to not see newly configured values on the first run.
**Solution:**
- Delayed the import of `mcp_server` module until after config is updated
- Added `config.reload()` call after environment variables are set
- This ensures the MCP server sees the latest configuration values
Added support for customizing the MCP server transport:
- `--transport`: Specify transport type (e.g., 'stdio', 'streamable-http')
- `--port`: Specify port number when using streamable-http …
=> Fix MCP server config loading and add transport/port options

defog/llm/config/settings.py, setup.py
- Adds support for reading API keys from the config file in `chat_async`
- Aligns behavior with the MCP server's text-to-sql tool
- Updated `LLMConfig._setup_api_keys()` to fall back to config file when environment variables are not set
- Priority order: Environment variables (highest) → Config file (fallback)
- Config file is located at `~/.defog/config.json`
Tested locally by:
1. Verifying API keys are read from environment variables when set
2. Removing environment variables and confirming fallback to config file works
3. Running `ruff check` to ensure code style compliance
=> Add config file support to chat_async API key loading

defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/openai_provider.py, defog/llm/tools/handler.py, defog/llm/utils.py, defog/llm/utils_function_calling.py, docs/api-reference.md, setup.py, tests/test_llm_tool_calls.py
- Fixed parallel tool calling implementation to be a runtime parameter instead of a config setting
- Updated all providers (OpenAI, Anthropic, Gemini) to accept `parallel_tool_calls` parameter
- Simplified tests by removing config-based testing in favor of parameter-based testing
- Added `parallel_tool_calls` parameter to `chat_async()` function with default value of `False`
- Modified provider implementations to pass this parameter through the call chain
- Updated tool handler to use the parameter instead of config setting
- Refactored tests to use the new parameter approach
- Updated API reference documentation
=> Fix parallel tool calling across providers

defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/openai_provider.py, defog/llm/utils.py, defog/llm/utils_function_calling.py, setup.py, tests/test_llm_post_response_hook.py, tests/test_llm_tool_calls.py, tests/test_post_response_hook.py, tests/test_tool_output_validation.py
This lets us track the responses as they come, in addition to the existing `post_tool_function`.
- Add optional post_response_hook callback to base provider interface
- Implement hook calls in oai, gemini and anthropic providers after each response
- Add tests for the new functionality
Usage:
```python
async def log_responses(
response: Any,
messages: List[Dict[str, Any]],
) -> None:
logging.info(response)
def calculate(expression: str) -> str:
"""Simple calculation tool for testing."""
try:
result = eval(expression, {"__builtins__": {}}, {})
return f"The result is {result}"
except:
return f"Error evaluating {expression}"
response = await chat_async(
provider="openai",
model="gpt-4o-mini",
messages=[{"role": "user", "content": "Calculate 25 * 4"}],
tools=[calculate], …
```
=> Add optional post_response_hook for openai, anthropic and gemini providers

defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/openai_provider.py, defog/llm/tools/handler.py, defog/llm/utils.py
- Refactored `image_result_keys` from being passed through 4-6 function calls to being a property on `ToolHandler`
- Reduces parameter passing complexity and improves code maintainability
- Maintains backward compatibility with existing API
1. Added `image_result_keys` as an optional parameter to `ToolHandler.__init__()`
2. Updated `create_tool_handler_with_budget()` to accept and pass `image_result_keys`
3. Modified all `process_tool_results_with_images()` calls to use `handler.image_result_keys`
4. Removed `image_result_keys` parameter from `execute_chat()` and `process_response()` methods across all providers
5. Preserved the parameter in the public `chat_async()` API for backward compatibility
=> refactor: Move image_result_keys to ToolHandler property

defog/llm/providers/anthropic_provider.py, defog/llm/providers/base.py, defog/llm/providers/deepseek_provider.py, defog/llm/providers/gemini_provider.py, defog/llm/providers/mistral_provider.py, defog/llm/providers/openai_provider.py, defog/llm/tools/handler.py, defog/llm/utils.py, docs/api-reference.md, tests/test_llm_tool_calls.py
- Added `tool_output_max_tokens` parameter to `chat_async` to make tool output size limits configurable
- Default limit remains 10,000 tokens for backward compatibility
- Setting `tool_output_max_tokens=-1` disables the check entirely
```python
from defog import chat_async
response = await chat_async(
provider="openai",
model="gpt-4",
messages=[{"role": "user", "content": "Query the database"}],
tools=[sql_query_tool]
)
response = await chat_async(
provider="openai",
model="gpt-4",
messages=[{"role": "user", "content": "Get all records from large table"}],
tools=[sql_query_tool],
tool_output_max_tokens=50000  # Allow up to 50k tokens for a tool output
)
response = await chat_async(
provider="openai",
model="gpt-4",
messages=[{"role": "user", "content": "Export full dataset"}], …
```
=> feat: Add configurable tool output cutoff size
