defog-ai/defog

- defog/__init__.py
> small change to get query

- defog/__init__.py
- defog/cli.py
- setup.py
Earlier, only postgres had a password input
> Added password input to all database types

- defog/cli.py
- defog/serve.py
- setup.py
This will let users run a webserver on their machine with no added complications
> added cli webserver

- README.md
- defog/__init__.py
- defog/cli.py
- defog/query.py
- setup.py
Currently a draft PR. Must check after adding actual data to databricks
> Add databricks support

- defog/cli.py
- requirements.txt
**Motivation**: Make usability improvements to the CLI onboarding process
**Changes made**:
- Automatically detects and removes trailing spaces are accidentally input by user
- Lets users see the API key as they are typing it to detect typos immediately. Otherwise, they can only be detected much later and the entire process has to be repeated 
- Gives users feedback with asterisks as passwords are being typed
- Detects and removes http or https in host input for postgres and redshift
- Adds link to metadata cookbook for easy reference
- Gives a status update to user when metadata file is being uploaded
> Made usability improvements to CLI onboarding

- defog/__init__.py
- defog/cli.py
- setup.py
Additionally, refactored the `generate_db_schema` function to take in `scan` and `bool` parameters, to make it more extendable.
> Made database scanning optional and prompted users

- defog/__init__.py
- defog/cli.py
- defog/util.py
- requirements.txt
- setup.py
Added files that were previously only in `requirements.txt` to `install_requires`. Also added convenience methods that are not directly relevant for onboarding here, but are useful when using this library as a part of our upcoming methods.
> Add relevant files to install_requires, and added convenience methods for metadata generation

- defog/__init__.py
- defog/cli.py
- setup.py
Additionally, sent an additional `db_type` argument to the `/update_metadata` endpoint
> Removed old and obsolete code + introduced base_url param for easier local testing

- defog/cli.py
Small cosmetic UX improvement found while dogfooding.
> Hide the print statements when there's no reason.

- README.md
- defog/admin_methods.py
- defog/cli.py
Update README
Fix CLI functionality for `defog quota` to point to the updated endpoint and print out the per-month usage
> CLI + documentation

- defog/query.py
- setup.py
This is to prevent downstream problems with the frontend
> De-duplicate columns when multiple columns with the exact string are mentioned

- README.md
- defog/__init__.py
- defog/cli.py
- defog/generate_schema.py
- defog/query.py
- setup.py
- tests/test_defog.py
Corresponding PR in the backend repo coming up soon.
To ensure that this runs locally, one must also download the [ODBC Driver for SQLServer](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16). On Macs, you _might_ also have to reinstall openssl with `brew reinstall openssl@3`
> Re-enabled SQLServer

- defog/admin_methods.py
- defog/query.py
- defog/query_methods.py
- setup.py
- tests/test_query.py
This is a convenience method that accompanies PR #119 in the backend repo
> Adding the `temp` param to query and integration methods

- defog/generate_schema.py
defog is not running on python version 3.8 adding this will fix the problem
> fix defog to also run on python version 3.8

- defog/generate_schema.py
- defog/query.py
- setup.py
Fix an edge case for `async_execute_query_once` where it would error out if data was found.
> Async query bugfix

- defog/generate_schema.py
- setup.py
1-line PR that automatically adds enum values to column descriptions
> Add enum values to column description

- .github/workflows/main.yml
- defog/llm/models.py
- defog/llm/utils.py
- defog/llm/utils_function_calling.py
- requirements.txt
- setup.py
- tests/test_llm.py
- tests/test_llm_tool_calls.py
- tests/test_util.py
Add a `chat_async` function to this library, so we can easily make LLM calls to popular providers (`OpenAI`, `Anthropic`, `Gemini`, `Together`).
Supports structured outputs, tool use, reasoning_effort, automated retries with exponential backoff, and more. Please refer to `tests/test_llm.py` and `tests/test_llm_tool_call.py` for more details.
```python
from defog.llm.utils import chat_async
messages_sql = [
{
"role": "system",
"content": "Your task is to generate SQL given a natural language question and schema of the user's database. Do not use aliases. Return only the SQL without backticks.",
},
{
"role": "user",
"content": f"""Question: What is the total number of orders?
Schema:
CREATE TABLE orders (
order_id int,
customer_id int,
employee_id int,
order_date date
);
""",
}
]
await …
```
> DEF-721 Add llm utils to `defog` library, in order to make it easy to make LLM calls to popular providers

- defog/llm/utils.py
- defog/llm/utils_function_calling.py
- defog/llm/utils_mcp.py
- requirements.txt
- tests/test_llm.py
Adds support for the gpt-4.1, o4-mini, and o3 series
> Add support for new OpenAI models

- defog/query.py
- tests/test_query.py
- ensure DB connections/cursors are managed via context managers
- update async functions to close connections safely
> Fix thread safety in DB query helpers

- README.md
- defog/llm/__init__.py
- defog/llm/memory/__init__.py
- defog/llm/memory/compactifier.py
- defog/llm/memory/history_manager.py
- defog/llm/memory/token_counter.py
- defog/llm/utils_memory.py
- requirements.txt
- tests/test_memory.py
This PR implements automatic memory compactification for managing long conversations with LLMs, based on Anthropic's cookbook approach.
- **Automatic summarization**: Intelligently summarizes older messages when token threshold is exceeded
- **System message preservation**: System messages are always preserved, never summarized
- **Flexible configuration**: Customizable thresholds, preservation rules, and summary sizes
- **Provider agnostic**: Works with all supported LLM providers (OpenAI, Anthropic, Gemini, Together)
- **Accurate token counting**: Uses tiktoken for OpenAI models with fallback for other providers
1. **MemoryManager**: Tracks conversation history and manages compactification
2. **TokenCounter**: Accurate token counting using tiktoken
3. **Compactifier**: Generates …
> feat: Add memory compactification for long conversations

- defog/llm/orchestrator.py
- Implement exponential backoff retry logic for individual task execution
- Add circuit breaker pattern to prevent cascading failures in parallel execution
- Enhance error reporting with detailed classification and tracing
- Add model fallback mechanism for recovery from model-specific errors
- Implement task decomposition as final fallback for complex failing tasks
> Add comprehensive error handling and retry system to orchestrator

- defog/llm/citations.py
- defog/llm/code_interp.py
- defog/llm/utils_logging.py
- defog/llm/web_search.py
- defog/llm/youtube_transcript.py
- tests/test_youtube.py
• Add progress tracking and logging for LLM tools (citations, code interpreter, web search, YouTube transcript)
• Create reusable `ToolProgressTracker` and `SubTaskLogger` utilities in `utils_logging.py`
• Implement YouTube transcript functionality using Gemini API
• Add end-to-end test for YouTube transcript tool
• **Progress Tracking**: Progress bars with spinners, percentages, and elapsed time for all tools
• **Logging**: Provider info, subtask status, and result summaries for better visibility
• **YouTube Transcription**: New tool to convert YouTube videos to timestamped transcripts
• **Testing**: End-to-end test for YouTube functionality
> Add logging and progress bars for LLM tools + YouTube transcript

- defog/llm/youtube_transcript.py
- requirements.txt
- tests/test_youtube.py
- add configurable system instructions and task descriptions, instead of hard-coding this to be a transcript only generator (the defaults are still around transcript generation, though)
- unrelatedly - added black to requirements for easier autoformatting
> Make the Youtube Summary function more extensible

- .gitignore
- defog/llm/orchestrator.py
- examples/orchestrator_dynamic_example.py
- examples/setup_cricket_db.py
- Fixed multiple potential infinite loop scenarios in the orchestrator
- Added comprehensive safeguards to prevent runaway execution
1. **Recursion Depth Tracking** (`max_recursion_depth`): Prevents infinite agent creation chains by limiting how deep agents can create other agents
2. **Cycle Detection**: Implemented proper DFS-based cycle detection in task dependency resolution to catch circular dependencies before execution
3. **Global Retry Limit** (`max_total_retries`): Added a global counter that limits total retries across all tasks
4. **Decomposition Depth Limit** (`max_decomposition_depth`): Prevents infinite task decomposition recursion
5. **Global Timeout** (`global_timeout`): Enforces an overall time limit with proper async task cancellation
6. **Dependency Mapping Fix**: Fixed …
> Fix infinite loops in orchestrator

- .gitignore
- CLAUDE.md
- README.md
- defog/__init__.py
- defog/admin_methods.py
- defog/async_generate_schema.py
- defog/async_query_methods.py
- defog/cli.py
- defog/generate_schema.py
- defog/health_methods.py
- defog/llm/orchestrator.py
- defog/llm/sql.py
- defog/llm/sql_generator.py
- defog/local_metadata_extractor.py
- defog/metadata_cache.py
- defog/query.py
- defog/query_methods.py
- defog/util.py
- examples/orchestrator_dynamic_example.py
- examples/setup_cricket_db.py
- requirements.txt
- tests/test_async_defog.py
- tests/test_defog.py
- tests/test_duckdb_connector.py
- tests/test_local_metadata_extractor.py
- tests/test_metadata_cache.py
- tests/test_query.py
- tests/test_sql_generator.py
- tests/test_sqlite_connector.py
- tests/test_youtube.py
- Add DuckDB as a supported database engine
- Update schema generation and query methods to handle DuckDB
- Migrate examples to use DuckDB instead of SQLite
- Update setup scripts and requirements
- Added DuckDB to requirements.txt
- Updated `__init__.py` and README with DuckDB configuration
- Modified schema generation and query generation to support DuckDB syntax
- Migrated cricket database setup and orchestrator example to use DuckDB
- Added .duckdb files to .gitignore
> Add DuckDB support

- defog/llm/pdf_data_extractor.py
- defog/llm/providers/anthropic_provider.py
- examples/orchestrator_dynamic_example.py
- examples/pdf_analysis_example.py
- examples/pdf_data_extractor_example.py
- examples/podcast_analyzer.py
- examples/schema_documentation_example.py
- examples/setup_cricket_db.py
• Added comprehensive cost and token tracking to PDF data extraction
• Enhanced logging with detailed step-by-step progress reporting  
• Updated example with better cost analysis and token usage reporting
> Improve PDF data extraction with cost and token tracking

- defog/llm/pdf_data_extractor.py
- Optimized table extraction in PDF data extractor to use columnar format instead of repeating field names
- Updated schema generation to use `columns` and `data` array structure
- Modified extraction prompts to guide LLM toward more efficient output format
(the results below are for a test with an Apple Financial Statement PDF)
- **28% reduction in output tokens**: 14,235 → 10,251 tokens
- **27% reduction in file size**: 22KB → 16KB  
- **Eliminates repetitive column names** in every table row
- **More efficient token usage** for large financial tables
- Modified `_generate_pydantic_schema()` to create columnar table schemas
- Updated extraction task prompts with clear guidance for columnar format
- Tables now use format: `{"columns": [...], "data": [[...], [...]]}`
> Optimize PDF table extraction with columnar format

- README.md
- tests/test_html_data_extractor.py
- tests/test_image_data_extractor.py
- tests/test_image_support.py
- tests/test_llm.py
- tests/test_orchestrator_e2e.py
- tests/test_util.py
- tests/test_web_search.py
- Removed feedback-related tests as the feedback functionality has been removed
- Parallelized test execution to improve performance
- Removed unnecessary print statements from tests
- Fixed incorrect tests and test parameters
- Updated README to use `--upgrade` flag in installation instructions
- Parallelized web search tests using asyncio.gather for better performance
> Update tests and improve test performance

- .gitignore
- .serena/memories/code_style_conventions.md
- .serena/memories/project_entrypoints.md
- .serena/memories/project_overview.md
- .serena/memories/suggested_commands.md
- .serena/memories/task_completion_checklist.md
- .serena/project.yml
- README.md
> Add artifacts generated by the Serena MCP server to git history

- README_MCP.md
- defog/__init__.py
- defog/async_query_methods.py
- defog/cli.py
- defog/cli_wizard.py
- defog/config.py
- defog/llm/citations.py
- defog/llm/code_interp.py
- defog/llm/providers/anthropic_provider.py
- defog/llm/providers/deepseek_provider.py
- defog/llm/providers/gemini_provider.py
- defog/llm/providers/mistral_provider.py
- defog/llm/providers/openai_provider.py
- defog/llm/providers/together_provider.py
- defog/llm/web_search.py
- defog/llm/youtube.py
- defog/mcp_server.py
- defog/query_methods.py
- defog/server_config_manager.py
- requirements.txt
- setup.py
- tests/test_code_interp.py
- tests/test_sql_generator.py
- Added interactive CLI wizard for easy server setup
- Implemented centralized configuration management with persistence
- Migrated all providers to use unified config system
- New `cli_wizard.py` provides guided setup for API keys and database connections
- Automatically launches when environment variables are missing
- Secure password input handling with `pwinput`
- New `defog db` command for managing database configuration
- `config.py` module provides unified configuration access
- Configuration persisted in `~/.defog/config.json`
- Fallback from environment variables to saved config
- All providers migrated from `os.getenv()` to `config.get()`
- Changed `cache_metadata` default from `True` to `False` for safer opt-in behavior
- Updated documentation in README_MCP.md
- Added …
> Add interactive CLI wizard and centralized configuration system

- defog/llm/image_utils.py
- defog/llm/pdf_data_extractor.py
- defog/llm/pdf_processor.py
- defog/llm/providers/anthropic_provider.py
- defog/llm/text_data_extractor.py
- tests/test_text_data_extractor.py
- Refactored content conversion functions in `image_utils.py` to properly handle all content types, not just text and images
- Removed system prompt from PDF processor to fix prompt parsing issues
- Removed location_hint field from PDF and text data extractors as it was not being used effectively
1. **Content Conversion Functions** (`image_utils.py`):
- Fixed `convert_to_anthropic_format`, `convert_to_openai_format`, and `convert_to_gemini_parts` to pass through all content types unchanged if they're not images
- Previously these functions were only handling text and image blocks, causing other content types to be dropped
2. **PDF Processor** (`pdf_processor.py`):
- Removed separate system message and merged it with the user message
- This fixes issues with prompt parsing and improves …
> Fix content conversion functions for document and other outputs
